
GET http://localhost:5001/api/todos

###

POST http://localhost:5001/api/todos
content-type: application/json


{
    "name":"totodfs"
}

###

DELETE  http://localhost:5001/api/todos/5f90035fd660de3057c17

###

POST  http://localhost:5001/api/users
content-type: application/json


{
    "name":"totodfs",
    "email":"niffco.riqsdot@free.fr",
    "password":"sdlmkfjslmdfjslkdfj"
}

###


POST  http://localhost:5001/api/auth
content-type: application/json


{
    "email":"niffco.ridot@free.fr",
    "password":"sdlmkfjslmdfjslkdfj"
}

###