
GET http://localhost:5001/api/todos

###

POST http://localhost:5001/api/todos
content-type: application/json


{
    "name":"totods"
}

###

DELETE  http://localhost:5001/api/todos/5f90035fd660de3057c17
