
GET http://localhost:5001/api/todos

###

POST http://localhost:5001/api/todos
content-type: application/json


{
    "name":"totodfs"
}

###

DELETE  http://localhost:5001/api/todos/5f90035fd660de3057c17

###

POST  http://localhost:5001/api/users

###